stages:
  - test

variables:
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2
  COMPOSE_DOCKER_CLI_BUILD: "1"
  DOCKER_BUILDKIT: "1"

test:
  stage: test
  image: docker:27
  services:
    - name: docker:27-dind
      command: ["--mtu=1460"]
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH
  before_script:
    - docker version
    - docker compose version
    - cd admin_panel
    - |
      cat > ../.env.test << 'EOF'
      POSTGRES_DB=cinema
      POSTGRES_USER=cinema
      POSTGRES_PASSWORD=cinema
      POSTGRES_HOST=postgres_test
      POSTGRES_PORT=5432

      DJANGO_SUPERUSER_USERNAME=test_admin
      DJANGO_SUPERUSER_EMAIL=test_admin@example.com
      DJANGO_SUPERUSER_PASSWORD=test_password
      EOF
  script:
    - docker compose -f test-compose.yml up --build --abort-on-container-exit --exit-code-from admin_panel_test
  after_script:
    - docker compose -f test-compose.yml down -v